name: trailviewer_flutter
description: Cleveland Metroparks TrailView viewer for Flutter
version: 0.0.3
homepage: https://github.com/cleveland-metroparks/trailviewer_flutter
repository: https://github.com/cleveland-metroparks/trailviewer_flutter

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.6

# flutter:
#   uses-material-design: true